# Generated by Django 6.1.1 on 2026-09-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10, null=True),
        ),
    ]
