# Generated by Django 6.1.1 on 2026-10-04 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_userprofile_branch_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_on_hand', models.IntegerField(default=0)),
                ('physical_qty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.branch')),
            ],
            options={
                'ordering': ['barcode'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'barcode'), name='unique_product_barcode_per_branch')],
            },
        ),
    ]
